// <auto-generated />
using System;
using AidatTakip.Data.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AidatTakip.Migrations
{
    [DbContext(typeof(AidatTakipContext))]
    [Migration("20250521080922_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");

            modelBuilder.Entity("AidatTakip.Models.Aidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaireId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("TEXT");

                    b.Property<int>("Yil")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DaireId", "Ay", "Yil")
                        .IsUnique();

                    b.ToTable("Aidatlar");
                });

            modelBuilder.Entity("AidatTakip.Models.Apartman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Apartmanlar");
                });

            modelBuilder.Entity("AidatTakip.Models.Daire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartmanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DaireSorumlu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApartmanId");

                    b.ToTable("Daireler");
                });

            modelBuilder.Entity("AidatTakip.Models.Odeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AidatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AidatId");

                    b.ToTable("Odemeler");
                });

            modelBuilder.Entity("AidatTakip.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Siteler");
                });

            modelBuilder.Entity("AidatTakip.Models.Aidat", b =>
                {
                    b.HasOne("AidatTakip.Models.Daire", "Daire")
                        .WithMany("Aidatlar")
                        .HasForeignKey("DaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Daire");
                });

            modelBuilder.Entity("AidatTakip.Models.Apartman", b =>
                {
                    b.HasOne("AidatTakip.Models.Site", "Site")
                        .WithMany("Apartmanlar")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("AidatTakip.Models.Daire", b =>
                {
                    b.HasOne("AidatTakip.Models.Apartman", "Apartman")
                        .WithMany("Daireler")
                        .HasForeignKey("ApartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartman");
                });

            modelBuilder.Entity("AidatTakip.Models.Odeme", b =>
                {
                    b.HasOne("AidatTakip.Models.Aidat", "Aidat")
                        .WithMany("Odemeler")
                        .HasForeignKey("AidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aidat");
                });

            modelBuilder.Entity("AidatTakip.Models.Aidat", b =>
                {
                    b.Navigation("Odemeler");
                });

            modelBuilder.Entity("AidatTakip.Models.Apartman", b =>
                {
                    b.Navigation("Daireler");
                });

            modelBuilder.Entity("AidatTakip.Models.Daire", b =>
                {
                    b.Navigation("Aidatlar");
                });

            modelBuilder.Entity("AidatTakip.Models.Site", b =>
                {
                    b.Navigation("Apartmanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
